console.log("Solution for question 1");
let a = 10.45;
a = 20.55;
console.log(a);
console.log("Solution for question 2");
console.log("Hello, World.");
console.log("Hello, JavaScript.");
console.log("Solution for question 3");
let b = 10;
console.log("My num is " + b);
console.log("Solution for question 4");
let num = 8;
console.log(num + "x 1 = " + num * 1);
console.log(num + "x 2 = " + num * 2);
console.log(num + "x 3 = " + num * 3);
console.log(num + "x 4 = " + num * 4);
console.log(num + "x 5 = " + num * 5);
console.log(num + "x 6 = " + num * 6);
console.log(num + "x 7 = " + num * 7);
console.log(num + "x 8 = " + num * 8);
console.log(num + "x 9 = " + num * 9);
console.log(num + "x 10 = " + num * 10);

console.log("Solution for question 5");
let a = 1042;
let b = 7;
let quo = Math.floor(a / b);
let rem = a % b;
console.log(quo + " " + rem);
